#!/bin/bash
echo
export webaddy=http://localhost
export author="Your Name"
export journal=/absolute/path/to/journal

# get date
export y=`date +%Y`
export m=`date +%m`
export d=`date +%d`

# is today the first journal entry of the year?
# does the year folder not exist? if yes, then make it.
if [ ! -e $journal/$y ]
  then echo "today's year, month and day directories do not exist; making them"
  mkdir $journal/$y
  export ly=$(($y-1))
  export lm=`ls -1 $journal/$ly | tail -n 1`
  mkdir $journal/$y/$m
  export ld=`ls -1 $journal/$ly/$lm | tail -n 1`
  mkdir $journal/$y/$m/$d
  cp -r $journal/$ly/$lm/$ld/* $journal/$y/$m/$d/.
  echo old: $journal/$ly/$lm/$ld
  echo new: $journal/$y/$m/$d
# is today the first journal entry of the month?
elif [ ! -e $journal/$y/$m ]
  then echo "today's month and day directories do not exist; making them"
  mkdir $journal/$y/$m
  mkdir $journal/$y/$m/$d
  export ly=$y
  export lm=`ls -1 $journal/$ly | tail -n 2 | head -n 1`
  export ld=`ls -1 $journal/$ly/$lm | tail -n 1`
  cp -r $journal/$ly/$lm/$ld/* $journal/$y/$m/$d/.
  echo old: $journal/$ly/$lm/$ld
  echo new: $journal/$y/$m/$d
# or are you just blogging for the first time today?
elif [ ! -e $journal/$y/$m/$d ]
  then echo "today's directory does not exist; making it"
  export ly=$y
  export lm=$m
  export ld=`ls -1 $journal/$ly/$lm | tail -n 1`
  mkdir $journal/$y/$m/$d
  cp -r $journal/$ly/$lm/$ld/* $journal/$y/$m/$d/.
  echo old: $journal/$ly/$lm/$ld
  echo new: $journal/$y/$m/$d
else
  echo "today's entry exists"
  echo now: $journal/$y/$m/$d
fi

# update dates at head of index.md
echo
echo "updating header"
n=`wc -l $journal/$y/$m/$d/index.md | cut -d ' ' -f 1`
am=`date +%b`
ad=`date +%`
date +'# [%d %b %Y %a]('$webaddy'/journal/%Y/%m/%d)' > tmp
echo '###### '$author >> tmp
tail -n $(($n-2)) $journal/$y/$m/$d/index.md >> tmp
mv tmp $journal/$y/$m/$d/index.md
echo

# update archive link summaries

echo moving to root of journal...
pushd $journal
echo

echo generating archive
echo > ../archive.md
echo '---' >> ../archive.md
echo >> ../archive.md
echo '## archive' >> ../archive.md
echo >> ../archive.md
echo '//' >> ../archive.md
for j in `find . -name index.md`; do
i=`pwd`
j=`echo $j | tail -c +2`
k=`echo $j | tail -c +2 | head -c +10`
l=`echo $j | head -c +12`index.shtml
echo \[$k\]\($webaddy/journal$l\)' //' >> ../archive.md
done
echo

echo exiting journal directory
popd
